const ProjectPage = () => {
    return (
    <>
        <h3>ProjectPage</h3>
        <hr />
        <div>
            <h3>Project A</h3>
            <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis voluptas esse error quibusdam! Officiis quis deserunt, incidunt similique alias quaerat temporibus hic iste adipisci aliquid, iure, blanditiis nisi est voluptatem.</span><span>Expedita repudiandae, iste quod dolor commodi enim maiores? Est inventore doloribus earum alias consequatur exercitationem, repudiandae laudantium iste libero, accusantium similique quod consectetur modi voluptatem illum odit culpa quidem labore.</span><span>Tempora consequatur blanditiis harum alias. Eos culpa natus quos quod, alias atque, fuga cumque velit vitae non omnis, nisi saepe dignissimos ipsa ut quae nulla sunt similique ex distinctio ea!</span><span>Sint dolore enim consectetur ex, nihil sapiente eius ad a. Fugiat molestiae modi accusamus officiis fuga suscipit rem perferendis maiores beatae distinctio. Reprehenderit repellendus, velit beatae amet quibusdam voluptates deleniti.</span><span>Enim eum dolorem ratione aliquid laboriosam inventore itaque deleniti suscipit. Inventore modi ratione nulla eveniet, quas praesentium ad, iste, accusantium natus tempora ea culpa. Excepturi architecto nemo possimus cupiditate animi!</span></p>
        </div>
        <div>
            <h3>Project B</h3>
            <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis voluptas esse error quibusdam! Officiis quis deserunt, incidunt similique alias quaerat temporibus hic iste adipisci aliquid, iure, blanditiis nisi est voluptatem.</span><span>Expedita repudiandae, iste quod dolor commodi enim maiores? Est inventore doloribus earum alias consequatur exercitationem, repudiandae laudantium iste libero, accusantium similique quod consectetur modi voluptatem illum odit culpa quidem labore.</span><span>Tempora consequatur blanditiis harum alias. Eos culpa natus quos quod, alias atque, fuga cumque velit vitae non omnis, nisi saepe dignissimos ipsa ut quae nulla sunt similique ex distinctio ea!</span><span>Sint dolore enim consectetur ex, nihil sapiente eius ad a. Fugiat molestiae modi accusamus officiis fuga suscipit rem perferendis maiores beatae distinctio. Reprehenderit repellendus, velit beatae amet quibusdam voluptates deleniti.</span><span>Enim eum dolorem ratione aliquid laboriosam inventore itaque deleniti suscipit. Inventore modi ratione nulla eveniet, quas praesentium ad, iste, accusantium natus tempora ea culpa. Excepturi architecto nemo possimus cupiditate animi!</span></p>
        </div>
        <div>
            <h3>Project C</h3>
            <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis voluptas esse error quibusdam! Officiis quis deserunt, incidunt similique alias quaerat temporibus hic iste adipisci aliquid, iure, blanditiis nisi est voluptatem.</span><span>Expedita repudiandae, iste quod dolor commodi enim maiores? Est inventore doloribus earum alias consequatur exercitationem, repudiandae laudantium iste libero, accusantium similique quod consectetur modi voluptatem illum odit culpa quidem labore.</span><span>Tempora consequatur blanditiis harum alias. Eos culpa natus quos quod, alias atque, fuga cumque velit vitae non omnis, nisi saepe dignissimos ipsa ut quae nulla sunt similique ex distinctio ea!</span><span>Sint dolore enim consectetur ex, nihil sapiente eius ad a. Fugiat molestiae modi accusamus officiis fuga suscipit rem perferendis maiores beatae distinctio. Reprehenderit repellendus, velit beatae amet quibusdam voluptates deleniti.</span><span>Enim eum dolorem ratione aliquid laboriosam inventore itaque deleniti suscipit. Inventore modi ratione nulla eveniet, quas praesentium ad, iste, accusantium natus tempora ea culpa. Excepturi architecto nemo possimus cupiditate animi!</span></p>
        </div>
        <div>
            <h3>Project D</h3>
            <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis voluptas esse error quibusdam! Officiis quis deserunt, incidunt similique alias quaerat temporibus hic iste adipisci aliquid, iure, blanditiis nisi est voluptatem.</span><span>Expedita repudiandae, iste quod dolor commodi enim maiores? Est inventore doloribus earum alias consequatur exercitationem, repudiandae laudantium iste libero, accusantium similique quod consectetur modi voluptatem illum odit culpa quidem labore.</span><span>Tempora consequatur blanditiis harum alias. Eos culpa natus quos quod, alias atque, fuga cumque velit vitae non omnis, nisi saepe dignissimos ipsa ut quae nulla sunt similique ex distinctio ea!</span><span>Sint dolore enim consectetur ex, nihil sapiente eius ad a. Fugiat molestiae modi accusamus officiis fuga suscipit rem perferendis maiores beatae distinctio. Reprehenderit repellendus, velit beatae amet quibusdam voluptates deleniti.</span><span>Enim eum dolorem ratione aliquid laboriosam inventore itaque deleniti suscipit. Inventore modi ratione nulla eveniet, quas praesentium ad, iste, accusantium natus tempora ea culpa. Excepturi architecto nemo possimus cupiditate animi!</span></p>
        </div>
        <div>
            <h3>Project E</h3>
            <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis voluptas esse error quibusdam! Officiis quis deserunt, incidunt similique alias quaerat temporibus hic iste adipisci aliquid, iure, blanditiis nisi est voluptatem.</span><span>Expedita repudiandae, iste quod dolor commodi enim maiores? Est inventore doloribus earum alias consequatur exercitationem, repudiandae laudantium iste libero, accusantium similique quod consectetur modi voluptatem illum odit culpa quidem labore.</span><span>Tempora consequatur blanditiis harum alias. Eos culpa natus quos quod, alias atque, fuga cumque velit vitae non omnis, nisi saepe dignissimos ipsa ut quae nulla sunt similique ex distinctio ea!</span><span>Sint dolore enim consectetur ex, nihil sapiente eius ad a. Fugiat molestiae modi accusamus officiis fuga suscipit rem perferendis maiores beatae distinctio. Reprehenderit repellendus, velit beatae amet quibusdam voluptates deleniti.</span><span>Enim eum dolorem ratione aliquid laboriosam inventore itaque deleniti suscipit. Inventore modi ratione nulla eveniet, quas praesentium ad, iste, accusantium natus tempora ea culpa. Excepturi architecto nemo possimus cupiditate animi!</span></p>
        </div>
    
    </>
    )
}

export default ProjectPage